# Generated by Django 5.1.6 on 2025-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('complete_address', models.CharField(max_length=250)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('years_employed', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_term', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('existing_loans', models.BooleanField()),
            ],
        ),
    ]
