# Generated by Django 5.1.6 on 2025-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_carloanapplication_car_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloanapplication',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
