# Generated by Django 5.1.6 on 2025-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_carloanapplication_down_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carloanapplication',
            name='employment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carloanapplication',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carloanapplication',
            name='marital_status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carloanapplication',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carloanapplication',
            name='years_employed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
