# Generated by Django 5.1.6 on 2025-07-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_carloanapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_start_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, default='Ongoing', max_length=200, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.carloanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='CarLoanPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.carloandisbursement')),
            ],
        ),
    ]
