# Generated by Django 5.1.6 on 2025-07-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_carloandisbursement_carloanpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloandisbursement',
            name='end_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
