# Generated by Django 5.1.6 on 2025-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_carloandisbursement_end_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carloandisbursement',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
