# Generated by Django 5.1.6 on 2025-07-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0008_rename_end_data_carloandisbursement_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloandisbursement',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
