# Generated by Django 5.1.6 on 2025-07-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0009_carloandisbursement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloandisbursement',
            name='is_fully_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
