# Generated by Django 5.1.6 on 2025-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0010_carloandisbursement_is_fully_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloandisbursement',
            name='is_celebrate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
