# Generated by Django 5.1.6 on 2025-07-10 15:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0011_carloandisbursement_is_celebrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carloandisbursement',
            old_name='end_date',
            new_name='repay_date',
        ),
        migrations.RenameField(
            model_name='carloandisbursement',
            old_name='disbursement_start_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='carloanpayments',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='carloandisbursement',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carloandisbursement',
            name='frequency',
            field=models.CharField(blank=True, default='monthly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carloandisbursement',
            name='payment_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carloanpayments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carloanpayments',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carloanpayments',
            name='penalty_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carloanpayments',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carloanpayments',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt'),
        ),
    ]
