# Generated by Django 5.1.6 on 2025-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0012_rename_end_date_carloandisbursement_repay_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloandisbursement',
            name='last_penalty_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carloandisbursement',
            name='no_penalty_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carloandisbursement',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
