# Generated by Django 5.1.6 on 2025-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0013_carloandisbursement_last_penalty_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloanpayments',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
