# Generated by Django 5.1.6 on 2025-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0016_carloancommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloandisbursement',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
