# Generated by Django 5.1.6 on 2025-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0018_remove_carloandisbursement_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloancommission',
            name='track_system_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
