# Generated by Django 5.1.6 on 2025-07-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0019_carloancommission_track_system_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloanpayments',
            name='is_reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
