# Generated by Django 5.1.6 on 2025-07-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0020_carloanpayments_is_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloanapplication',
            name='is_reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
