# Generated by Django 5.1.6 on 2025-07-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0021_carloanapplication_is_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carloanapplication',
            name='car_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
