# Generated by Django 5.1.6 on 2025-07-15 06:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0022_alter_carloanapplication_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloanapplication',
            name='back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='back_image'),
        ),
        migrations.AddField(
            model_name='carloanapplication',
            name='front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='front_image'),
        ),
    ]
