# Generated by Django 5.1.6 on 2025-07-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0023_carloanapplication_back_carloanapplication_front'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carloanapplication',
            old_name='back',
            new_name='back_id',
        ),
        migrations.RenameField(
            model_name='carloanapplication',
            old_name='front',
            new_name='front_id',
        ),
    ]
