# Generated by Django 5.1.6 on 2025-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_loanadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='monthly_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
