# Generated by Django 5.1.6 on 2025-03-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='monthly_salary',
        ),
    ]
