# Generated by Django 5.1.6 on 2025-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_verificationrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequests',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
