# Generated by Django 5.1.6 on 2025-03-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_verificationrequests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.CharField(default='not applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrequests',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
