# Generated by Django 5.1.6 on 2025-03-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequests',
            name='tin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
