# Generated by Django 5.1.6 on 2025-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_verificationrequests_tin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequests',
            name='image',
        ),
        migrations.RemoveField(
            model_name='verificationrequests',
            name='tin_number',
        ),
        migrations.AddField(
            model_name='verificationrequests',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequests',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequests',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
