# Generated by Django 5.1.6 on 2025-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_verificationrequests_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_borrower',
            field=models.BooleanField(default=True),
        ),
    ]
