# Generated by Django 5.1.6 on 2025-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customuser_is_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_borrower',
            field=models.BooleanField(default=False),
        ),
    ]
