# Generated by Django 5.1.6 on 2025-04-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
