# Generated by Django 5.1.6 on 2025-04-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
