# Generated by Django 5.1.6 on 2025-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_good_payer',
            field=models.BooleanField(default=False),
        ),
    ]
