# Generated by Django 5.1.6 on 2025-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_customuser_is_good_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequests',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
