# Generated by Django 5.1.6 on 2025-05-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_verificationrequests_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequests',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
