# Generated by Django 5.1.6 on 2025-05-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_verificationrequests_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
