# Generated by Django 5.1.6 on 2025-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_customuser_is_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blacklisted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
