# Generated by Django 5.1.6 on 2025-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayments',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
