# Generated by Django 5.1.6 on 2025-05-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0002_loanpayments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayments',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanpayments',
            name='penalty_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
