# Generated by Django 5.1.6 on 2025-05-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0003_loanpayments_is_penalty_loanpayments_penalty_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpayments',
            name='is_penalty',
        ),
    ]
