# Generated by Django 5.1.6 on 2025-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0004_remove_loanpayments_is_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayments',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
    ]
