# Generated by Django 5.1.6 on 2025-03-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanAdmin',
        ),
    ]
