# Generated by Django 5.1.6 on 2025-06-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='status',
        ),
    ]
