# Generated by Django 5.1.6 on 2025-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repayment_term', models.IntegerField()),
                ('payment_frequency', models.CharField(default='Monthly', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='LoanPlans',
        ),
    ]
