# Generated by Django 5.1.6 on 2025-03-16 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanplan_delete_loanplans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=255)),
                ('income_range', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanplan')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loantypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
