# Generated by Django 5.1.6 on 2025-03-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loanapplication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
