# Generated by Django 5.1.6 on 2025-03-22 16:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loanapplication_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='income_range',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='type',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='back_image'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='front_image'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_variation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='money_recieve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='other_sources_of_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='primary_income_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='primary_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_spend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
