# Generated by Django 5.1.6 on 2025-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_remove_loanapplication_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='money_recieve',
            new_name='money_receive',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='outstanding',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
