# Generated by Django 5.1.6 on 2025-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_rename_money_recieve_loanapplication_money_receive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
