# Generated by Django 5.1.6 on 2025-03-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
