# Generated by Django 5.1.6 on 2025-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loanapplication_borrowed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
