# Generated by Django 5.1.6 on 2025-03-24 15:55

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_loanapplication_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_selfie', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_selfie')),
                ('repay_date', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashout', models.CharField(blank=True, max_length=50)),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
