# Generated by Django 5.1.6 on 2025-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_loansubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
