# Generated by Django 5.1.6 on 2025-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_loansubmission_is_fully_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
