# Generated by Django 5.1.6 on 2025-03-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_loansubmission_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='frequency',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
