# Generated by Django 5.1.6 on 2025-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_loansubmission_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
