# Generated by Django 5.1.6 on 2025-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_loansubmission_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
