# Generated by Django 5.1.6 on 2025-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_loansubmission_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='is_celebrate',
            field=models.BooleanField(default=False),
        ),
    ]
