# Generated by Django 5.1.6 on 2025-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_loansubmission_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='last_penalty_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
