# Generated by Django 5.1.6 on 2025-05-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0021_loansubmission_last_penalty_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='no_penalty_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
