# Generated by Django 5.1.6 on 2025-05-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_loansubmission_no_penalty_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
