# Generated by Django 5.1.6 on 2025-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_loanapplication_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansubmission',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
