# Generated by Django 5.1.6 on 2025-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_alter_loansubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansubmission',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loansubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
